const questions = [ //eslint-disable-line
  [
    {
      id: 1,
      type: "text-input",
      title: "What is the syntax for declaring a variable in JavaScript?",
      body: "",
      correct: "var",
      topic: "JavaScript",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a JavaScript data type?",
      body: ["String", "Boolean", "Float", "Number"],
      correct: "Float",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are JavaScript frameworks?",
      body: ["Angular", "React", "Vue", "jQuery"],
      correct: ["Angular", "React", "Vue"],
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the output of the following code: console.log(2 + '2')?",
      body: "",
      correct: "22",
    },
    {
      id: 5,
      type: "selection",
      title: "Which keyword is used to exit a loop in JavaScript?",
      body: ["break", "continue", "return", "exit"],
      correct: "break",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are JavaScript array methods?",
      body: ["push()", "pop()", "slice()", "splice()"],
      correct: ["push()", "pop()", "slice()", "splice()"],
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the result of the expression '5' == 5?",
      body: "",
      correct: "true",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is used to add a comment in JavaScript?",
      body: ["//", "/* */", "<!-- -->", "##"],
      correct: "//",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are JavaScript string methods?",
      body: ["length()", "toUpperCase()", "trim()", "concat()"],
      correct: ["toUpperCase()", "trim()", "concat()"],
    },
    {
      id: 10,
      type: "text-input",
      title: "What is the result of the expression NaN === NaN?",
      body: "",
      correct: "false",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title: "What does PHP stand for?",
      body: "",
      correct: "Hypertext Preprocessor",
      topic: "PHP",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a PHP data type?",
      body: ["String", "Boolean", "Float", "Integer"],
      correct: "Float",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are PHP frameworks?",
      body: ["Laravel", "Symfony", "CodeIgniter", "Django"],
      correct: ["Laravel", "Symfony", "CodeIgniter"],
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the output of the following code: echo 'Hello, World!';?",
      body: "",
      correct: "Hello, World!",
    },
    {
      id: 5,
      type: "selection",
      title: "Which keyword is used to exit a loop in PHP?",
      body: ["break", "continue", "return", "exit"],
      correct: "break",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are PHP array functions?",
      body: [
        "array_push()",
        "array_pop()",
        "array_slice()",
        "array_splice()",
      ],
      correct: [
        "array_push()",
        "array_pop()",
        "array_slice()",
        "array_splice()",
      ],
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the result of the expression '5' == 5 in PHP?",
      body: "",
      correct: "true",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is used to add a comment in PHP?",
      body: ["//", "/* */", "<!-- -->", "##"],
      correct: "/* */",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are PHP string functions?",
      body: ["strlen()", "strtoupper()", "trim()", "concat()"],
      correct: ["strlen()", "strtoupper()", "trim()"],
    },
    {
      id: 10,
      type: "text-input",
      title: "What is the result of the expression 10 % 3 in PHP?",
      body: "",
      correct: "1",
    },
  ],
  [
    {
      id: 1,
      type: "checkbox",
      title: "Which of the following are block-level HTML elements?",
      body: ["<div>", "<span>", "<p>", "<a>"],
      correct: ["<div>", "<p>"],
      topic: "HTML",
    },
    {
      id: 2,
      type: "text-input",
      title: "What is the purpose of the <head> tag in HTML?",
      body: "",
      correct: "To contain meta-information about the HTML document",
    },
    {
      id: 3,
      type: "selection",
      title: "Which attribute is used to specify the URL of an external script file in HTML?",
      body: ["src", "href", "link", "script"],
      correct: "src",
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the purpose of the alt attribute in the <img> tag?",
      body: "",
      correct: "To provide alternative text for an image",
    },
    {
      id: 5,
      type: "selection",
      title: "Which tag is used to define a hyperlink in HTML?",
      body: ["<a>", "<link>", "<href>", "<url>"],
      correct: "<a>",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid HTML heading tags?",
      body: ["<h1>", "<h2>", "<h3>", "<h4>"],
      correct: ["<h1>", "<h2>", "<h3>", "<h4>"],
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the purpose of the <table> tag in HTML?",
      body: "",
      correct: "To create a table structure",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is NOT a valid HTML tag?",
      body: ["<div>", "<span>", "<header>", "<paragraph>"],
      correct: "<paragraph>",
    },
    {
      id: 9,
      type: "text-input",
      title: "What does HTML stand for?",
      body: "",
      correct: "HyperText Markup Language",
    },
    {
      id: 10,
      type: "checkbox",
      title: "Which of the following are valid HTML input types?",
      body: ["text", "number", "boolean", "email"],
      correct: ["text", "number", "email"],
    }
  ],
  [
    {
      id: 1,
      type: "checkbox",
      title: "Which of the following are valid CSS units of measurement?",
      body: ["px", "em", "%", "pt"],
      correct: ["px", "em", "%"],
      topic: "CSS",
    },
    {
      id: 2,
      type: "text-input",
      title: "What does CSS stand for?",
      body: "",
      correct: "Cascading Style Sheets",
    },
    {
      id: 3,
      type: "text-input",
      title: "What is the purpose of the display property in CSS?",
      body: "",
      correct: "To control how an element is displayed",
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the purpose of the padding property in CSS?",
      body: "",
      correct: "To control the spacing within an element",
    },
    {
      id: 5,
      type: "checkbox",
      title: "Which of the following are CSS selectors?",
      body: ["class", "id", "tag", "attribute"],
      correct: ["class", "id", "tag"],
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid CSS color values?",
      body: ["red", "#000000", "rgb(255, 255, 255)", "none"],
      correct: ["red", "#000000", "rgb(255, 255, 255)"],
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the purpose of the margin property in CSS?",
      body: "",
      correct: "To control the spacing around an element",
    },
    {
      id: 8,
      type: "selection",
      title: "Which property is used to change the background color of an element in CSS?",
      body: ["color", "background-color", "background", "background-image"],
      correct: "background-color",
    },
    {
      id: 9,
      type: "selection",
      title: "Which of the following is NOT a valid CSS property?",
      body: ["margin", "padding", "border", "spacing"],
      correct: "spacing",
    },
    {
      id: 10,
      type: "selection",
      title: "Which property is used to change the font size of an element in CSS?",
      body: ["font-size", "text-size", "font-style", "text-style"],
      correct: "font-size",
    }
  ],
  [],
  [],
  [],
  [],
  [],
  [],
];

