//eslint-disable-next-line
const questions = [
  [
    {
      id: 1,
      type: "text-input",
      title: "What is the syntax for declaring a variable in JavaScript?",
      body: "",
      correct: "var",
      topic: "JavaScript",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a JavaScript data type?",
      body: ["String", "Boolean", "Float", "Number"],
      correct: "Float",
      topic: "JavaScript",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are JavaScript frameworks?",
      body: ["Angular", "React", "Vue", "jQuery"],
      correct: ["Angular", "React", "Vue"],
      topic: "JavaScript",
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the output of the following code: console.log(2 + '2')?",
      body: "",
      correct: "22",
      topic: "JavaScript",
    },
    {
      id: 5,
      type: "selection",
      title: "Which keyword is used to exit a loop in JavaScript?",
      body: ["break", "continue", "return", "exit"],
      correct: "break",
      topic: "JavaScript",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are JavaScript array methods?",
      body: ["push()", "pop()", "slice()", "splice()"],
      correct: ["push()", "pop()", "slice()", "splice()"],
      topic: "JavaScript",
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the result of the expression '5' == 5?",
      body: "",
      correct: "true",
      topic: "JavaScript",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is used to add a comment in JavaScript?",
      body: ["//", "/* */", "<!-- -->", "##"],
      correct: "//",
      topic: "JavaScript",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are JavaScript string methods?",
      body: ["length()", "toUpperCase()", "trim()", "concat()"],
      correct: ["toUpperCase()", "trim()", "concat()"],
      topic: "JavaScript",
    },
    {
      id: 10,
      type: "text-input",
      title: "What is the result of the expression NaN === NaN?",
      body: "",
      correct: "false",
      topic: "JavaScript",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title: "What does PHP stand for? (hint: it's a recursive acronym)",
      body: "",
      correct: "PHP Hypertext Preprocessor",
      topic: "PHP",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a PHP data type?",
      body: ["String", "Boolean", "Float", "Integer"],
      correct: "Float",
      topic: "PHP",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are PHP frameworks?",
      body: ["Laravel", "Symfony", "CodeIgniter", "Django"],
      correct: ["Laravel", "Symfony", "CodeIgniter"],
      topic: "PHP",
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the output of the following code: echo 'Hello, World!';?",
      body: "",
      correct: "Hello, World!",
      topic: "PHP",
    },
    {
      id: 5,
      type: "selection",
      title: "Which keyword is used to exit a loop in PHP?",
      body: ["break", "continue", "return", "exit"],
      correct: "break",
      topic: "PHP",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are PHP array functions?",
      body: ["array_push()", "array_pop()", "array_slice()", "array_splice()"],
      correct: [
        "array_push()",
        "array_pop()",
        "array_slice()",
        "array_splice()",
      ],
      topic: "PHP",
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the result of the expression '5' == 5 in PHP?",
      body: "",
      correct: "true",
      topic: "PHP",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is used to add a comment in PHP?",
      body: ["//", "/* */", "<!-- -->", "##"],
      correct: "/* */",
      topic: "PHP",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are PHP string functions?",
      body: ["strlen()", "strtoupper()", "trim()", "concat()"],
      correct: ["strlen()", "strtoupper()", "trim()"],
      topic: "PHP",
    },
    {
      id: 10,
      type: "text-input",
      title: "What is the result of the expression 10 % 3 in PHP?",
      body: "",
      correct: "1",
      topic: "PHP",
    },
  ],
  [
    {
      id: 1,
      type: "checkbox",
      title: "Which of the following are block-level HTML elements?",
      body: ["<div>", "<span>", "<p>", "<a>"],
      correct: ["<div>", "<p>"],
      topic: "HTML",
    },
    {
      id: 2,
      type: "text-input",
      title: "What infromation is contained in the <head> tag in HTML?",
      body: "",
      correct: "meta-information",
      topic: "HTML",
    },
    {
      id: 3,
      type: "selection",
      title:
        "Which attribute is used to specify the URL of an external script file in HTML?",
      body: ["src", "href", "link", "script"],
      correct: "src",
      topic: "HTML",
    },
    {
      id: 4,
      type: "text-input",
      title:
        "Alt attribute in the <img> tag provides ******** text for an image.",
      body: "",
      correct: "Alternative",
      topic: "HTML",
    },
    {
      id: 5,
      type: "selection",
      title: "Which tag is used to define a hyperlink in HTML?",
      body: ["<a>", "<link>", "<href>", "<url>"],
      correct: "<a>",
      topic: "HTML",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid HTML heading tags?",
      body: ["<h1>", "<h2>", "<h3>", "<h4>"],
      correct: ["<h1>", "<h2>", "<h3>", "<h4>"],
      topic: "HTML",
    },
    {
      id: 7,
      type: "text-input",
      title:
        "Should you use an <h3> tag if you don't have an <h2> tag in your page?",
      body: "",
      correct: "No",
      topic: "HTML",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is NOT a valid HTML tag?",
      body: ["<div>", "<span>", "<header>", "<paragraph>"],
      correct: "<paragraph>",
      topic: "HTML",
    },
    {
      id: 9,
      type: "text-input",
      title: "What does HTML stand for?",
      body: "",
      correct: "HyperText Markup Language",
      topic: "HTML",
    },
    {
      id: 10,
      type: "checkbox",
      title: "Which of the following are valid HTML input types?",
      body: ["text", "number", "boolean", "email"],
      correct: ["text", "number", "email"],
      topic: "HTML",
    },
  ],
  [
    {
      id: 1,
      type: "checkbox",
      title: "Which of the following are valid CSS units of measurement?",
      body: ["px", "em", "%", "pt"],
      correct: ["px", "em", "%"],
      topic: "CSS",
    },
    {
      id: 2,
      type: "text-input",
      title: "What does CSS stand for?",
      body: "",
      correct: "Cascading Style Sheets",
      topic: "CSS",
    },
    {
      id: 3,
      type: "text-input",
      title:
        "What property would you use to control the display of an element?",
      body: "",
      correct: "Display",
      topic: "CSS",
    },
    {
      id: 4,
      type: "text-input",
      title: "Padding property controls the spacing ****** the element",
      body: "",
      correct: "Inside",
      topic: "CSS",
    },
    {
      id: 5,
      type: "checkbox",
      title: "Which of the following are CSS selectors?",
      body: ["class", "id", "tag", "attribute"],
      correct: ["class", "id", "tag"],
      topic: "CSS",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid CSS color values?",
      body: ["red", "#000000", "rgb(255, 255, 255)", "none"],
      correct: ["red", "#000000", "rgb(255, 255, 255)"],
      topic: "CSS",
    },
    {
      id: 7,
      type: "text-input",
      title: "Margin property controls the spacing ****** the element",
      body: "",
      correct: "Around",
      topic: "CSS",
    },
    {
      id: 8,
      type: "selection",
      title:
        "Which property is used to change the background color of an element in CSS?",
      body: ["bg", "background-color", "bg-color", "background-image"],
      correct: "background-color",
      topic: "CSS",
    },
    {
      id: 9,
      type: "selection",
      title: "Which of the following is NOT a valid CSS property?",
      body: ["margin", "padding", "border", "spacing"],
      correct: "spacing",
      topic: "CSS",
    },
    {
      id: 10,
      type: "selection",
      title:
        "Which property is used to change the font size of an element in CSS?",
      body: ["font-size", "text-size", "font-style", "text-style"],
      correct: "font-size",
      topic: "CSS",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title: "What function is used to render a React component?",
      body: "",
      correct: "render",
      topic: "React",
    },
    {
      id: 2,
      type: "selection",
      title:
        "Which lifecycle method is invoked immediately after a component is mounted?",
      body: [
        "componentDidMount",
        "componentDidUpdate",
        "componentWillUnmount",
        "render",
      ],
      correct: "componentDidMount",
      topic: "React",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are React state hooks?",
      body: ["useState", "useEffect", "useContext", "useReducer"],
      correct: ["useState", "useReducer"],
      topic: "React",
    },
    {
      id: 4,
      type: "text-input",
      title: "JSX allows writing **** in JavaScript",
      body: "",
      correct: "HTML",
      topic: "React",
    },
    {
      id: 5,
      type: "selection",
      title:
        "Which of the following is NOT a valid way to handle forms in React?",
      body: [
        "Controlled Components",
        "Uncontrolled Components",
        "Refs",
        "Stateful Components",
      ],
      correct: "Stateful Components",
      topic: "React",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are React component lifecycle methods?",
      body: [
        "constructor",
        "componentDidMount",
        "render",
        "componentWillUnmount",
      ],
      correct: ["componentDidMount", "componentWillUnmount"],
      topic: "React",
    },
    {
      id: 7,
      type: "text-input",
      title: "React is a JavaScript *****",
      body: "",
      correct: "Library",
      topic: "React",
    },
    {
      id: 8,
      type: "selection",
      title: "Which method is used to update the state in a React component?",
      body: ["setState", "updateState", "changeState", "modifyState"],
      correct: "setState",
      topic: "React",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are React component patterns?",
      body: [
        "Higher-Order Components",
        "Render Props",
        "Container Components",
        "Functional Components",
      ],
      correct: [
        "Higher-Order Components",
        "Render Props",
        "Functional Components",
      ],
      topic: "React",
    },
    {
      id: 10,
      type: "text-input",
      title:
        "**** help React identify which items have changed, are added, or are removed.",
      body: "",
      correct: "Keys",
      topic: "React",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title:
        "Node.js is a JavaScript runtime built on Chrome's ***** Javascript engine",
      body: "",
      correct: "V8",
      topic: "Node.js",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a core module in Node.js?",
      body: ["http", "fs", "path", "fetch"],
      correct: "fetch",
      topic: "Node.js",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are Node.js package managers?",
      body: ["npm", "yarn", "pip", "npx"],
      correct: ["npm", "yarn", "npx"],
      topic: "Node.js",
    },
    {
      id: 4,
      type: "text-input",
      title: "package.json file is used to manage project *******.",
      body: "",
      correct: "dependencies.",
      topic: "Node.js",
    },
    {
      id: 5,
      type: "selection",
      title:
        "Which of the following is used to handle asynchronous operations in Node.js?",
      body: ["callbacks", "promises", "async/await", "all of the above"],
      correct: "all of the above",
      topic: "Node.js",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are Node.js frameworks?",
      body: ["Express", "Meteor", "Django", "Koa"],
      correct: ["Express", "Meteor", "Koa"],
      topic: "Node.js",
    },
    {
      id: 7,
      type: "text-input",
      title:
        "The **** object provides variables and functions that are available anywhere in the application.",
      body: "",
      correct: "Global",
      topic: "Node.js",
    },
    {
      id: 8,
      type: "selection",
      title: "Which method is used to include modules in Node.js?",
      body: ["require()", "import", "use()", "add()"],
      correct: "require()",
      topic: "Node.js",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are valid Node.js event emitters?",
      body: ["EventEmitter", "fs", "http", "stream"],
      correct: ["EventEmitter", "fs", "http"],
      topic: "Node.js",
    },
    {
      id: 10,
      type: "text-input",
      title:
        "The process object provides information and control over the current Node.js *******.",
      body: "",
      correct: "process",
      topic: "Node.js",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title:
        "Git is a distributed *************** system for tracking changes in source code during software development.",
      body: "",
      correct: "version control",
      topic: "Git",
    },
    {
      id: 2,
      type: "selection",
      title: "Which command is used to create a new branch in Git?",
      body: ["git commit", "git branch", "git checkout", "git clone"],
      correct: "git branch",
      topic: "Git",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are valid Git states for a file?",
      body: ["untracked", "tracked", "modified", "stashed"],
      correct: ["untracked", "tracked", "modified"],
      topic: "Git",
    },
    {
      id: 4,
      type: "text-input",
      title:
        "A Git ********** is a storage location where a project's history, files, and metadata are stored.",
      body: "",
      correct: "repository",
      topic: "Git",
    },
    {
      id: 5,
      type: "selection",
      title:
        "Which command is used to apply changes in staged files to the repository in Git?",
      body: ["git push", "git commit", "git pull", "git merge"],
      correct: "git commit",
      topic: "Git",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid Git branching strategies?",
      body: [
        "Feature Branching",
        "Trunk-Based Development",
        "GitFlow",
        "Monorepo",
      ],
      correct: ["Feature Branching", "Trunk-Based Development", "GitFlow"],
      topic: "Git",
    },
    {
      id: 7,
      type: "text-input",
      title:
        "A Git ***** command combines changes from different branches into one branch.",
      body: "",
      correct: "merge",
      topic: "Git",
    },
    {
      id: 8,
      type: "selection",
      title: "Which command is used to view the commit history in Git?",
      body: ["git log", "git status", "git show", "git diff"],
      correct: "git log",
      topic: "Git",
    },
    {
      id: 9,
      type: "checkbox",
      title:
        "Which of the following are valid Git remote repository hosting services?",
      body: ["GitHub", "Bitbucket", "GitLab", "Subversion"],
      correct: ["GitHub", "Bitbucket", "GitLab"],
      topic: "Git",
    },
    {
      id: 10,
      type: "text-input",
      title:
        "A Git **** request is a request to merge changes from one branch into another.",
      body: "",
      correct: "pull",
      topic: "Git",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title: "What is the syntax for declaring an integer variable x in C?",
      body: "",
      correct: "int x;",
      topic: "C lang",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a valid data type in C?",
      body: ["int", "float", "string", "char"],
      correct: "string",
      topic: "C lang",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are control structures in C?",
      body: ["if-else", "for", "while", "switch"],
      correct: ["if-else", "for", "while", "switch"],
      topic: "C lang",
    },
    {
      id: 4,
      type: "text-input",
      title: 'What is the output of the following code: printf("%d", 5 / 2);?',
      body: "",
      correct: "2",
      topic: "C lang",
    },
    {
      id: 5,
      type: "selection",
      title: "Which keyword is used to define a function in C?",
      body: ["def", "function", "void", "return"],
      correct: "void",
      topic: "C lang",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid C operators?",
      body: ["+", "-", "*", "/", "%"],
      correct: ["+", "-", "*", "/", "%"],
      topic: "C lang",
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the result of the expression 'A' == 'a'?",
      body: "",
      correct: "false",
      topic: "C lang",
    },
    {
      id: 8,
      type: "selection",
      title:
        "Which of the following is used to denote a single-line comment in C?",
      body: ["//", "/* */", "<!-- -->", "##"],
      correct: "//",
      topic: "C lang",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are standard C library functions?",
      body: ["printf()", "scanf()", "strlen()", "toupper()"],
      correct: ["printf()", "scanf()", "strlen()"],
      topic: "C lang",
    },
    {
      id: 10,
      type: "text-input",
      title: "What is the result of the expression sizeof(int)?",
      body: "",
      correct: "4",
      topic: "C lang",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title: "The primary purpose of Goroutines in Go is ********** execution.",
      body: "",
      correct: "Concurrent",
      topic: "Go lang",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a valid data type in Go?",
      body: ["int", "float", "string", "char"],
      correct: "char",
      topic: "Go lang",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are control structures in Go?",
      body: ["if-else", "for", "while", "switch"],
      correct: ["if-else", "for", "switch"],
      topic: "Go lang",
    },
    {
      id: 4,
      type: "text-input",
      title: "What is the output of the following code: fmt.Println(5 / 2)?",
      body: "",
      correct: "2",
      topic: "Go lang",
    },
    {
      id: 5,
      type: "selection",
      title: "Which keyword is used to define a function in Go?",
      body: ["def", "function", "void", "func"],
      correct: "func",
      topic: "Go lang",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are valid Go operators?",
      body: ["+", "-", "*", "/", "%"],
      correct: ["+", "-", "*", "/", "%"],
      topic: "Go lang",
    },
    {
      id: 7,
      type: "text-input",
      title: "What is the result of the expression 'A' == 'a' in Go?",
      body: "",
      correct: "false",
      topic: "Go lang",
    },
    {
      id: 8,
      type: "selection",
      title:
        "Which of the following is used to denote a single-line comment in Go?",
      body: ["//", "/* */", "<!-- -->", "##"],
      correct: "//",
      topic: "Go lang",
    },
    {
      id: 9,
      type: "checkbox",
      title: "Which of the following are standard Go library functions?",
      body: [
        "fmt.Println()",
        "fmt.Scanf()",
        "strings.ToUpper()",
        "math.Sqrt()",
      ],
      correct: [
        "fmt.Println()",
        "fmt.Scanf()",
        "strings.ToUpper()",
        "math.Sqrt()",
      ],
      topic: "Go lang",
    },
    {
      id: 10,
      type: "text-input",
      title: 'What is the result of the expression len("gopher")?',
      body: "",
      correct: "6",
      topic: "Go lang",
    },
  ],
  [
    {
      id: 1,
      type: "text-input",
      title: "What is the default display property of a <div> element in CSS?",
      body: "",
      correct: "block",
      topic: "Various Web Dev",
    },
    {
      id: 2,
      type: "selection",
      title: "Which of the following is NOT a valid HTTP status code?",
      body: ["200", "404", "503", "300"],
      correct: "300",
      topic: "Various Web Dev",
    },
    {
      id: 3,
      type: "checkbox",
      title: "Which of the following are CSS preprocessor languages?",
      body: ["Sass", "Less", "HTML", "Stylus"],
      correct: ["Sass", "Less", "Stylus"],
      topic: "Various Web Dev",
    },
    {
      id: 4,
      type: "text-input",
      title: "The purpose of JavaScript is to make web pages ***********.",
      body: "",
      correct: "interactive",
      topic: "Various Web Dev",
    },
    {
      id: 5,
      type: "selection",
      title: "Which of the following is NOT a valid HTTP method?",
      body: ["GET", "POST", "UPDATE", "DELETE"],
      correct: "UPDATE",
      topic: "Various Web Dev",
    },
    {
      id: 6,
      type: "checkbox",
      title: "Which of the following are front-end JavaScript frameworks?",
      body: ["React", "Vue", "Angular", "Express"],
      correct: ["React", "Vue", "Angular"],
      topic: "Various Web Dev",
    },
    {
      id: 7,
      type: "selection",
      title:
        "Which CSS property is used to change the text color of an element?",
      body: ["color", "text-color", "font-color", "text-style"],
      correct: "color",
      topic: "Various Web Dev",
    },
    {
      id: 8,
      type: "selection",
      title: "Which of the following is NOT a valid MIME type?",
      body: ["text/html", "application/json", "image/xml", "audio/mpeg"],
      correct: "image/xml",
      topic: "Various Web Dev",
    },
    {
      id: 9,
      type: "checkbox",
      title:
        "Which of the following are commonly used back-end programming languages for web development?",
      body: ["Python", "Ruby", "Java", "MongoDB"],
      correct: ["Python", "Ruby", "Java"],
      topic: "Various Web Dev",
    },
    {
      id: 10,
      type: "checkbox",
      title: "Which of the following are valid HTML form input types?",
      body: ["text", "button", "image", "select"],
      correct: ["text", "button", "image"],
      topic: "Various Web Dev",
    },
  ],
];
